version: '3.5'
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports: 
        - '3306:3306'
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root1
      - MYSQL_PASSWORD=password
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
